name: Amusing
favicon: null
layout_spectrum: 0.4407054400071502
typography_spectrum: 0.023426726227626204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.42426056833937764
  lightness: 0.33078086096793413
  saturation: 0.08064521942287683
  rhythmicContrast: 0.07889734278433025
purpose: []
