color:
  brandStrength: 0.4242605683393776
  saturation: 0.08064521942287683
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.3307808609679341
  rhythmicContrast: 0.07889734278433025
title: AAmusing
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.4407054400071502
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
name: AAmusing
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0234267262276262
